feat: ようこそメッセージの追加
approvers/OreOreBot2 pull request #1028
Opened 2023-09-04 15:33 UTC by m1sk9

### Type of Change:

新規追加

### Details of implementation (実施内容)

限界開発鯖に新しいメンバーが参加した際にメンバーデータ登録などを示した埋め込みをようこそメッセージとして送信する機能を作成しました.

![CleanShot 2023-09-05 at 00 33 19@2x](https://github.com/approvers/OreOreBot2/assets/82575685/98e5781c-ea43-4eef-af96-d3d290a12749)

2023-09-04 17:31 UTC, MikuroXina requested changes

2023-09-04 17:31 UTC, MikuroXina commented on src/service/output.ts
> +
```suggestion
```
`WelcomeMessage` にとって `sendEmbed` は要らないかと

2023-09-04 17:31 UTC, MikuroXina commented on src/adaptor/proxy/member.ts
> +type AllMemberModel = NewMember;
```suggestion
import type { NewMember as AllMemberModel } from '../../service/welcome-message.js';
```
こう書くくらいなら別名で `import` したほうがよいかと

2023-09-04 17:31 UTC, MikuroXina commented on src/adaptor/proxy/member.ts
> +});
```suggestion
const map = ({ id, user }: GuildMember): AllMemberModel => ({
  userId: id as Snowflake,
  isBot: user.bot
});
```
もっと楽に書けます

2023-09-05 14:54 UTC, m1sk9 commented on src/adaptor/proxy/member.ts
> +type AllMemberModel = NewMember;
Fixed https://github.com/approvers/OreOreBot2/pull/1028/commits/17237327fa8e50c853f9f96424520ad06fc67317

2023-09-05 15:00 UTC, m1sk9 commented on src/service/output.ts
> +
これは今後機能拡張のために追加したものです. (もしかして: 不要)

2023-09-05 23:38 UTC, MikuroXina commented on src/service/output.ts
> +
ようこそメッセージを送るのに特に誰にも宛てずにメッセージを送るのはちょっと考えにくいです

2023-09-05 23:44 UTC, m1sk9 commented on src/service/output.ts
> +
どっちかというと今後 #玄関 に何らかのメッセージを送る機能を作るのを想定していた

2023-09-05 23:46 UTC, MikuroXina commented on src/service/output.ts
> +
そうなってくるとこれ以上 `Output` 系を増やすよりかは, チャンネル ID と Embed を指定して送るインターフェイスを用意しておいたほうがよさそうです. 抽象化し過ぎていて冗長になってしまいます

2023-09-05 23:47 UTC, m1sk9 commented on src/service/output.ts
> +
なるほど

2023-09-06 09:27 UTC, MikuroXina approved these changes

2023-09-06 09:27 UTC, merged