chore: Yarn Workspaces への移行
approvers/OreOreBot2 pull request #1056
Opened 2023-09-17 07:59 UTC by m1sk9

close #998 

### Details of implementation (実施内容)

Yarn Workspaces に移行し, それぞれのパッケージを `@oreorebot2/bot`, `@oreorebot2/docs` の2つに分割しました.

- 大半の変更はファイル間の移動です. 
- このビルドの Docker Images のサイズが 527MB -> 915MB に倍増してしまいました. 主な原因として `@oreorebot2/docs` パッケージを含めてしまっているからだと推測されます.( Yarn Workspaces の仕様上, `@oreorebot2/docs` パッケージを含めないと Docker Image のビルド時に失敗するため致し方ないと考えていますが, Docker に詳しい人が居たら指摘してくれると助かります. 私にはこれが限界です.)
- `CONTRIBUTING.md` は別で変更したい内容があるため, 今回のPRには含めていません.

2023-09-17 09:15 UTC, MikuroXina requested changes

2023-09-17 09:15 UTC, MikuroXina commented on packages/bot/package.json
> +    "vitest": "^0.34.0"
`ts-node` の peer dependency かつ直接の依存関係でもある `@types/node` と `typescript` を足しておきましょう

2023-09-17 09:15 UTC, MikuroXina commented on Dockerfile
> +    && cp -r /src/packages/bot/{build,assets} .
この `Dockerfile` はルートに配置されていますが, 本来はボットのものだったはずです. `packages/bot` に移動させて, それをビルドする CI にしましょう

2023-09-17 16:54 UTC, m1sk9 commented
イメージのビルド自体は成功していますが最適化作業中, 以下の問題が存在しています.

- Production Install を行うと Husky を実行しようとしてしまいビルドに失敗する.
![image](https://github.com/approvers/OreOreBot2/assets/82575685/4ac16bcc-3ae4-4da0-8cde-3f0c74975d6e)

最適化を後にする場合はこのPRをマージすることができます.
依存関係が絡むPRのため, 放置すればするほど @renovate のPRにより conflict 範囲が広くなってしまうためできれば早くマージしたいところ.

2023-09-17 22:20 UTC, MikuroXina requested changes
最適化はあとでいいので, コードカバレッジの CI のカバレッジファイルのパスを直しましょう. それで Approve できます

2023-09-17 22:22 UTC, MikuroXina requested changes

2023-09-17 22:22 UTC, MikuroXina commented on .github/codeql/codeql-config.yml
> +  - '**.md'
```suggestion
  - '**/*.md'
```
そのようなワイルドカードは不正です

2023-09-18 04:09 UTC, m1sk9 commented on .github/codeql/codeql-config.yml
> +  - '**.md'
Fixed https://github.com/approvers/OreOreBot2/pull/1056/commits/cea701af501b413c56903994457e957ecf8d7454

2023-09-18 04:12 UTC, MikuroXina approved these changes

2023-09-18 04:13 UTC, merged