chore(action): add actionlint.yml
approvers/OreOreBot2 pull request #183
Opened 2022-05-13 09:49 UTC by KisaragiEffective

**Issue:** #182

### Type of Change:

* create `.github/workflow/actionlint.yml

### Cause of the Problem (問題の原因)

#182 に書いてあるので省略

### Dealing with Problems (問題への対処)

#182 と同様なので省略

### Details of implementation (実施内容)

#182 と同様なので省略

### Additional Information (追加情報)

2022-05-13 11:18 UTC, MikuroXina requested changes
`actionlint.yml` 内の `reviewdog/action-actionlint` の `with` に `required` なものがすべて記述されていない (`reviewdog/action-actionlint` 側の不具合と思われる) のですが, それにもかかわらず action-actionlint がその不整合を報告していないので正しく動作していないおそれがあります. 別の Action などを検討してもらいたいです.

2022-05-18 09:32 UTC, KisaragiEffective commented
@MikuroXina [確認しました](https://github.community/t/what-happens-if-both-required-and-default-was-set-in-input-clause/250872)が、`default`と`required: true`の組み合わせは、明示的に提供されなかった場合`default`で指定された値にフォールバックするという動作をするようです。
そのため、指摘されたような不具合は存在しないものと考えました。

2022-05-18 09:54 UTC, MikuroXina approved these changes
あまり依存すべきでない仕様だと思いますが, 現状は問題ないので ***Approve***

2022-05-18 09:56 UTC, KisaragiEffective commented
merge

2022-05-18 09:57 UTC, merged