feat: avoid echo back when `!stfu` was deleted
approvers/OreOreBot2 pull request #251
Opened 2022-06-09 12:31 UTC by KisaragiEffective

close #250

**Issue:** #250

### Type of Change:
feat: メッセージの内容が正確に`!stfu`だった場合は当該メッセージを出さないようにした

### Cause of the Problem (問題の原因)
既存の実装の仕様

### Dealing with Problems (問題への対処)
当該コミットにおいて変更を加えた

### Details of implementation (実施内容)
当該コミット

### Additional Information (追加情報)
N/A

2022-06-09 12:34 UTC, MikuroXina requested changes
`stfu` と `DeletionRepeater` の機能の間には関係性が無いので, 直接書くのは望ましくないです. 無視するパターンをコンストラクタで受け取るようにしてみてはどうでしょうか.

2022-06-09 14:44 UTC, MikuroXina requested changes

2022-06-09 14:44 UTC, MikuroXina commented on src/service/deletion-repeater.ts
> +  }
```suggestion
  constructor(private readonly isIgnoreTarget: (content: string) => boolean) {}
```
TypeScript の機能でまとめておくとよいでしょう.

2022-06-09 14:44 UTC, MikuroXina commented on src/service/index.ts
> +    new DeletionRepeater((content) => content === '!stfu'),
述語が複雑化することが予想されるので, これは定数として分けてほしいです.

2022-06-09 17:31 UTC, KisaragiEffective commented on src/service/deletion-repeater.test.ts
> +    content: 'Wall Is Stop',
```suggestion
    content: 'Wall Is Not Stop',
```

2022-07-23 14:04 UTC, m2en approved these changes

2022-07-23 14:05 UTC, MikuroXina approved these changes

2022-07-23 14:08 UTC, merged