feat: version コマンドを追加
approvers/OreOreBot2 pull request #255
Opened 2022-06-11 09:00 UTC by MikuroXina

### Type of Change:

機能の新規追加

### Cause of the Problem (問題の原因)

自動更新が成功したかどうかの確認などで, 現在起動してるボットのバージョンが何であるのか調べたいことがありました. 今まではこれをヘルプメッセージやコマンドの動作の変化などで確かめることがありましたが, 効率が悪いことでした.

### Dealing with Problems (問題への対処)

MessageQuote のようにアクティビティに自身のバージョンを表示することも考えましたが, ひとまずはユーザ一覧を見に行かなくても確認できるコマンドとして実装することにしました.

### Details of implementation (実施内容)

- `version` コマンドを追加

### Additional Information (追加情報)

この機能の単純さから, テストは不要と判断したため追加していません.

2022-06-11 12:11 UTC, meru92s requested changes

2022-06-11 12:11 UTC, meru92s commented on src/service/version.ts
> +      title: 'はらちょバージョン',
タイトルリンクにそのバージョンのリリースページ ( https://github.com/approvers/OreOreBot2/releases )を載せるといいかも

2022-06-11 12:11 UTC, meru92s commented on package.json
> +    "predebug": "yarn gen-version",
`prebuild` ならわかるんですが、 `predebug` はいらないかも？

2022-06-11 12:34 UTC, MikuroXina commented on package.json
> +    "predebug": "yarn gen-version",
`debug` の場合も, 生成したファイルが存在しなかったらファイルを開けなくて失敗するので必要です.

2022-06-11 12:37 UTC, MikuroXina commented on src/service/version.ts
> +      title: 'はらちょバージョン',
73d6abe で対応しました.

2022-06-13 23:55 UTC, m2en approved these changes

2022-06-14 00:22 UTC, merged