feat: ユーザー情報コマンドの追加
approvers/OreOreBot2 pull request #375
Opened 2022-08-03 13:00 UTC by m2en

close #341

### Type of Change:

新規追加: `userinfo` (`COMMAND`)

### Details of implementation (実施内容)

`!userinfo <id>` で指定ユーザーの情報を参照する機能を追加します。

2022-08-03 13:03 UTC, m2en commented
テスト忘れてた

2022-08-03 14:19 UTC, MikuroXina requested changes

2022-08-03 14:19 UTC, MikuroXina commented on src/adaptor/discord/user.ts
> +export class DiscordUserManager implements UserStatsRepository {
同じ「Discord の Guild の情報を取得する」責務を担うクラスである `DiscordMemberStats` が `member-stats.ts` にあるので, そちらに `implements` するインターフェイスを追記する形で移行したほうがよいと思います. 似たようなコードの繰り返しが減ります.

2022-08-03 14:19 UTC, MikuroXina commented on src/service/command/user-info.ts
> +    }
可変な変数が以降のスコープに残り続けてしまうので, この `joinedTimeStamp` を作る処理は関数分けしてほしいです.

2022-08-03 14:19 UTC, MikuroXina commented on src/service/command/user-info.ts
> +        name: 'アカウントカラー',
```suggestion
        name: 'プロフィールカラー',
```
Discord 上ではこうなっています

2022-08-03 14:19 UTC, MikuroXina commented on src/service/command/user-info.ts
> +        value: bot ? 'True' : 'False',
```suggestion
        name: 'ユーザ種別',
        value: bot ? 'ボット' : '人類',
```
ちょっと限界っぽい感じにしたい

2022-08-03 14:19 UTC, MikuroXina commented on src/service/command/user-info.ts
> +        name: 'ユーザー名+Discord Tag',
```suggestion
        name: 'Discord Tag',
```
`ユーザ名#数字4桁` のことを Discord Tag というようなので

2022-08-03 14:19 UTC, MikuroXina commented on src/service/command/user-info.ts
> +        value: `${userId}`,
ここのように, 文字列変数 1 つだけをテンプレート文字列にかけてしまっている部分がいくつかあります. そのまま変数を書くだけでいいので直してください.

2022-08-03 14:29 UTC, m2en commented on src/service/command/user-info.ts
> +        name: 'ユーザー名+Discord Tag',
`#` の後の四桁だけがDiscord Tagですね

参考: [Custom Discord Tags with Nitro - Discord ヘルプセンター](https://support.discord.com/hc/en-us/articles/360000270351)

2022-08-04 18:36 UTC, m2en commented on src/adaptor/discord/user.ts
> +export class DiscordUserManager implements UserStatsRepository {
`fetchStats` 関数を `member-stats.ts` に持っていくって感じ?
理解力なくてちょっとわからない

2022-08-05 02:43 UTC, MikuroXina commented on src/adaptor/discord/user.ts
> +export class DiscordUserManager implements UserStatsRepository {
`implements` をこのように追記してこのクラスで `fetchStats` を実装するということです. `DiscordUserManager` は削除してください.
```ts
export class DiscordMemberStats
  implements MemberStats, MembersWithRoleRepository, UserStatsRepository
{
```

2022-08-05 17:57 UTC, MikuroXina requested changes

2022-08-05 17:57 UTC, MikuroXina commented on src/adaptor/discord/member-stats.ts
> +      hoistRoleId: member.roles.hoist?.id as Snowflake | undefined
null 合体演算子にすべきかと. ついでに `joinedAt` のように定数として括りだした方が見やすいです.
```
      hoistRoleId: member.roles.hoist?.id as Snowflake ?? undefined
```

2022-08-05 17:57 UTC, MikuroXina commented on src/adaptor/discord/member-stats.ts
> +      joinedAt: joinedAt,
```suggestion
      joinedAt,
```
冗長です

2022-08-05 17:57 UTC, MikuroXina commented on src/adaptor/discord/member-stats.ts
> +    const createAt = member.user.createdAt;
```
    const createdAt = member.user.createdAt;
```
typo と思われるので

2022-08-05 17:57 UTC, MikuroXina commented on src/service/command/user-info.ts
> +import { Snowflake } from '../../model/id.js';
```suggestion
import type { Snowflake } from '../../model/id.js';
```
`import type` しましょう

2022-08-06 02:47 UTC, MikuroXina requested changes

2022-08-06 02:47 UTC, MikuroXina commented on src/adaptor/discord/member-stats.ts
> +      createdAt: createdAt,
```suggestion
      createdAt,
```
冗長です

2022-08-06 02:47 UTC, MikuroXina commented on src/adaptor/discord/member-stats.ts
> +import {
```suggestion
import type {
```
`import type` しましょう

2022-08-06 02:47 UTC, MikuroXina commented on src/server/index.ts
> +const userManager = new DiscordMemberStats(client, GUILD_ID as Snowflake);
`DiscordMemberStats` のインスタンスはすでに 133 行目に存在します. 新しく作らないでください.

2022-08-06 02:47 UTC, MikuroXina commented on src/service/command/user-info.ts
> +}
命名が変ですし同じ意味の処理が重複しています. `makeDiscordTimeStamp` のような名前にして 1 つの関数にまとめましょう

2022-08-06 03:35 UTC, m2en commented on src/service/command/user-info.ts
> +}
`joinedAt` が `undefined` である可能性があるからどういう返り値にすべきなのかが思いつかない

2022-08-06 03:38 UTC, MikuroXina commented on src/service/command/user-info.ts
> +}
いえ, 逆に考えるんです. `createdAt` は `undefined` にならないんですから, `undefined` になる可能性がある方のと同じ処理が使いまわせます.

2022-08-06 04:35 UTC, MikuroXina requested changes

2022-08-06 04:35 UTC, MikuroXina commented on src/adaptor/discord/member-stats.ts
> +    const hoistRoleId = (member.roles.hoist?.id as Snowflake) ?? null;
```suggestion
    const hoistRoleId = (member.roles.hoist?.id as Snowflake) ?? undefined;
```
`Snowflake | undefined` の型になっていたのでこうするべきかと

2022-08-06 04:35 UTC, MikuroXina commented on src/service/command/user-info.test.ts
> +import { Snowflake } from '../../model/id.js';
```suggestion
import type { Snowflake } from '../../model/id.js';
```
`import type` しましょう

2022-08-06 04:35 UTC, MikuroXina commented on src/service/command/user-info.ts
> +        name: 'メンバーリストロール(最上位)',
最上位ロールというわけでもなくちょっとわかりにくいので、「メンバーリストの分類ロール」くらいの感じでよいかと

2022-08-06 04:35 UTC, MikuroXina commented on src/service/command/user-info.ts
> +        name: '参加日時',
```suggestion
        name: 'サーバー参加日時',
```
ちょっと曖昧なので

2022-08-06 06:06 UTC, MikuroXina approved these changes

2022-08-06 06:06 UTC, merged