docs: セキュリティポリシーを追加
approvers/OreOreBot2 pull request #466
Opened 2022-09-10 16:11 UTC by m2en

### Type of Change:

新規追加

### Details of implementation (実施内容)

セキュリティポリシーを追加します。

脆弱性を見つけた際は [me@m2en.dev](mailto:me@m2en.dev) に連絡するよう、記載しています。

### Additional Information (追加情報)

2022-09-11 04:53 UTC, MikuroXina requested changes

2022-09-11 04:53 UTC, MikuroXina commented on SECURITY.md
> +OreOreBot2 自身、または Node.js の依存関係に関する脆弱性を発見した際は [me@m2en.dev](mailto:me@m2en.dev) までご連絡ください。
```suggestion
OreOreBot2 自身の脆弱性を発見した際は [me@m2en.dev](mailto:me@m2en.dev) までご連絡ください。
```
依存関係に関しては報告されるだけ無駄だと思います. その依存関係側のパッケージ等の対応完了を待ったり一時的なワークアラウンドを設けたりすることになりますから.

2022-09-11 04:53 UTC, MikuroXina commented on SECURITY.md
> +| バージョン 1 ( `v1.x.x` ) | ✅        | [2022/02/27](https://github.com/approvers/OreOreBot2/releases/tag/v1.0.0) | 未定             |
```md
| `1.x.y` | ✅        | [2022/02/27](https://github.com/approvers/OreOreBot2/releases/tag/v1.0.0) | 未定             |
```
バージョンのところに「バージョン」を重ねて書く必要はないかと (表の空白などの関係で Suggest にできませんでした)

2022-09-11 04:53 UTC, MikuroXina commented on SECURITY.md
> +<!-- me@m2en.dev の所有者は @m2en(https://github.com/m2en) です。-->
このコメントアウトは何でしょうか

2022-09-11 04:53 UTC, MikuroXina commented on SECURITY.md
> +(当リポジトリの Issue や、Twitter の公開スレッドなど、外部から見えてしまう場所での報告はご遠慮ください。)
```suggestion
当リポジトリの Issue や、Twitter の公開スレッドなど、外部から見えてしまう場所での報告はご遠慮ください。
```
大事な文章の括弧書きは避けましょう.

2022-09-11 04:54 UTC, m2en commented on SECURITY.md
> +<!-- me@m2en.dev の所有者は @m2en(https://github.com/m2en) です。-->
`me@m2en.dev` の所有者を表記しておきたかったんですが、ここに記載しても意味ないですね
消します

2022-09-11 05:03 UTC, MikuroXina requested changes

2022-09-11 05:03 UTC, MikuroXina commented on SECURITY.md
> +当リポジトリの Issue や、Twitter の公開スレッドなど、外部から見えてしまう場所での報告はご遠慮ください。
この後に新しい段落で, 報告にこういう情報を入れてほしいみたいなのがあったほうがいいかと. 参考: https://github.com/github/docs/security/policy

2022-09-11 09:05 UTC, MikuroXina requested changes

2022-09-11 09:05 UTC, MikuroXina commented on SECURITY.md
> +- 脆弱性に関連するソースコードの場所 (tag, branch, commit, permalink)
```suggestion
- 脆弱性に関連するソースコードのタグ、コミットハッシュ、permlink など
```
この場合の location を場所と訳するのは変かと

2022-09-11 16:51 UTC, m2en commented
@shun-shobon も、見てくれると嬉しい

2022-09-11 17:37 UTC, MikuroXina requested changes

2022-09-11 17:37 UTC, MikuroXina commented on SECURITY.md
> +OreOreBot2 自身の脆弱性を発見した際は** [me@m2en.dev](mailto:me@m2en.dev) まで GPG 鍵で暗号化を行ってから**ご連絡ください。
```suggestion
OreOreBot2 自身の脆弱性を発見した際は **[me@m2en.dev](mailto:me@m2en.dev) 宛に下記 PGP 鍵で暗号化を施して** ご連絡ください。
```
Bold が壊れてます

2022-09-12 06:10 UTC, MikuroXina approved these changes

2022-09-12 08:06 UTC, shun-shobon commented on SECURITY.md
> +[pgp_keys.asc](https://keybase.io/merunno/pgp_keys.asc?fingerprint=6e23c654c587e55dfafa8d4715db72f06f2acc5c)
鍵のフィンガープリントもその場に載せておくと信頼性が高まります。

2022-09-12 14:56 UTC, shun-shobon approved these changes

2022-09-12 14:57 UTC, merged