feat: ダイスコマンドの作成(仮あん)
approvers/OreOreBot2 pull request #473
Opened 2022-09-13 11:38 UTC by raiga0310

close #

### Type of Change:

新規追加：ダイスコマンドの追加
### Cause of the Problem (問題の原因)

### Dealing with Problems (問題への対処)

### Details of implementation (実施内容)
'!dice <num>d<num>`でダイスロールできるような機能の予定です。
はらちょで実装する必要がなければクローズします
また受け付ける数の制限は未定です。
### Additional Information (追加情報)

2022-09-18 14:56 UTC, raiga0310 commented
ダイスの制限について
主に使用用途はTRPGを考慮しているので、個数は20、出目は100での制限をかけようと思っています。また個数*出目で計算できる最大値で制限をかけるのもいいかと思っています。

2022-09-19 08:09 UTC, MikuroXina requested changes
CI が落ちているのは Prettier ではなく, tsc による型チェックで `server/index.ts` に必要な引数が不足しているエラーが出ているためです. 動作確認しましたか?

2022-09-19 08:09 UTC, MikuroXina commented on src/adaptor/dice-queen.ts
> +}
新しいアダプタのクラスを作らずに, `adaptor/random.ts` の `MathRandomGenerator` に実装する `interface` へ `DiceQueen` を追加してそこで実装するとよいでしょう

2022-09-19 08:09 UTC, MikuroXina commented on src/service/command/dice.ts
> +        description: 'ダイスは20面100個以下、最大値が200までの処理にしてね。'
20 面 100 個以下なのに最大値を 2000 ではなく 200 にしているのはなぜでしょうか?

2022-09-19 08:09 UTC, MikuroXina commented on src/service/command/dice.ts
> +    if (arg.match(/^(?!a-c,e-z)*$/)) {
この正規表現は正しく動作しません. `/^(?<num>\d+)[dD](?<faces>\d+)$/` のような名前付きマッチのパターンを用意して, この正常にマッチするか確認しつつマッチ結果を取り出すとよいでしょう

2022-09-19 08:09 UTC, MikuroXina commented on src/service/command/dice.ts
> +        'どのダイスを何個振るかの指定。6面ダイス2個であれば ‘!dice 2d6`のように入力してね',
ヘルプに `d` と `D` のどちらでも構わないことを明記すべきかと思います

2022-09-19 08:09 UTC, MikuroXina commented on src/service/command/dice.ts
> +  roll(faces: number, HowManyRoll: number): Array<number>;
```suggestion
  roll(faces: number, howManyRolls: number): Array<number>;
```
命名規則は camelCase にしてほしいです

2022-09-21 12:18 UTC, raiga0310 commented on src/service/command/dice.ts
> +        description: 'ダイスは20面100個以下、最大値が200までの処理にしてね。'
100面20個のつもりでしたが間違えました
最大値が200で制限している条件ですが、100面20個が最大という意味での制限ではなく、どちらもそれ以上は多すぎるという解釈で、LP問題の境界値みたいなものだと考えてくださればと思っています。

2022-09-21 12:28 UTC, MikuroXina commented on src/service/command/dice.ts
> +        description: 'ダイスは20面100個以下、最大値が200までの処理にしてね。'
しかし, ダイスの合計値が 200 を超えてしまうことが処理上の問題になるとは考えられないので無駄に制約を課しているように感じます. ダイスの合計値に制限を付けている理由が気になります

2022-09-21 13:16 UTC, MikuroXina requested changes

2022-09-21 13:16 UTC, MikuroXina commented on src/service/command/dice.ts
> +    const diceFaces = parseInt(arg2);
```suggestion
    const diceNum = parseInt(arg1, 10);
    const diceFaces = parseInt(arg2, 10);
```
基数を指定しましょう

2022-09-21 13:16 UTC, MikuroXina commented on src/service/command/dice.ts
> +        description: 'ダイスは100面20個以下、最大値が2000までの処理にしてね。'
判定条件とメッセージが噛み合っていません

2022-09-21 13:16 UTC, MikuroXina commented on src/service/command/dice.test.ts
> +  });
`200d1D3` や `0d6` などもっと意地悪なテストケースも足しましょう. また, 引数が大きすぎる判定のテストケースは条件ギリギリを狙ってテストするようにしましょう

2022-09-21 15:48 UTC, MikuroXina requested changes

2022-09-21 15:48 UTC, MikuroXina commented on src/service/command/dice.ts
> +        diceFaces * diceNum <= 2000
```suggestion
        diceNum <= 20
```
この条件なら掛けた値についての検査は不要かと

2022-09-21 15:48 UTC, MikuroXina commented on src/service/command/dice.ts
> +          'ダイスは非負整数で100面20個以下、最大値が2000までの処理にしてね。'
```suggestion
          'ダイスは非負整数で100面20個以下にしてね。'
```
最大値の説明は冗長だと思います

2022-09-21 15:48 UTC, MikuroXina commented on src/service/command/dice.ts
> +      description: `${arg} => ${diceSum}`
これはダイスボットという機能としての意見ですが, 各ダイスの出目のリストがないと不便そうです. それぞれのダイスの目を知りたいこともあるので

2022-09-21 15:48 UTC, MikuroXina commented on src/service/command/dice.ts
> +    if (!(arg1 !== undefined && arg2 !== undefined)) {
```suggestion
    if (arg1 === undefined || arg2 === undefined) {
```
二重否定は読みづらいのでこちらのほうがよいかと

2022-09-21 15:48 UTC, MikuroXina commented on src/service/command/dice.ts
> +    const regExState = /^(?<num>\d+)[dD](?<faces>\d+)$/;
正規表現はグローバルな定数にしてほしいです

2022-09-21 16:38 UTC, raiga0310 commented on src/service/command/dice.ts
> +      description: `${arg} => ${diceSum}`
後々オプション的なもので実装する予定です。ひとまず結果を出す実装のみを今PRでする予定です

2022-09-22 11:46 UTC, MikuroXina approved these changes

2022-09-22 11:48 UTC, merged