docs: READMEにおける環境変数の必須とデフォルト値に関する記述を修正
approvers/OreOreBot2 pull request #567
Opened 2022-11-03 17:05 UTC by m2en

### Type of Change:

修正

### Details of implementation (実施内容)

一部環境変数が設定されていなかった場合に通常はデフォルト値が使用されるはずなのに、 **すべて必須です。指定しなければ起動に失敗します。** と記述されていたため、修正しました。

2022-11-03 23:09 UTC, MikuroXina requested changes
現状だと「デフォルト値が無い変数は指定する必要がある、しないと起動に失敗する」という言い回しにして、表から必須かどうかのカラムを取り除いてもよいかと.

2022-11-03 23:51 UTC, m2en commented
> 現状だと「デフォルト値が無い変数は指定する必要がある、しないと起動に失敗する」という言い回しにして、表から必須かどうかのカラムを取り除いてもよいかと.
@MikuroXina 

今見ると、【デフォルト値】のカラム名が潰れていることがわかったので、それだけに済ませます。（必須のカラムはそのままでいい？）

2022-11-04 09:01 UTC, MikuroXina requested changes

2022-11-04 09:01 UTC, MikuroXina commented on README.md
> +(デフォルト値が設定されている変数は、起動時に指定されていない場合、そのデフォルト値が変数として使われます。)
段落全体の括弧書きはやめてください. あと表現が少し気になります.
```suggestion
起動時にデフォルト値が存在する変数の値が指定されていない場合は、そのデフォルト値が使われます。
```

2022-11-04 09:13 UTC, MikuroXina approved these changes

2022-11-04 09:13 UTC, merged