ci: CIの改善
approvers/OreOreBot2 pull request #651
Opened 2022-12-24 15:18 UTC by m2en

close #650 

### Type of Change:

修正等

### Details of implementation (実施内容)

@shun-shobon に #650 で指摘された内容をすべて改善しました。

- `setup-node`が使用されていない箇所への`setup-node`の追加
- `yarn install`時に`yarn.lock`を更新しないように`--frozen-lockfile`オプションの追加
- キャッシュの使用(`setup-node@3`以降であれば標準搭載されています)
- 全体的なActionのバージョン更新
- その他の改善

その他、CI の名前がガバガバだったので統一しました。他に気になる点があれば RC で指摘してください。

2022-12-24 15:27 UTC, shun-shobon requested changes

2022-12-24 15:27 UTC, shun-shobon commented on .github/actions/publish/action.yml
>          node-version: '16'
依存関係のキャッシュをする場合は明示的な指定が必要なので指定するようにしてください(他も同様)
ref: https://github.com/actions/setup-node#caching-global-packages-data
```suggestion
        node-version: '16'
        cache: yarn
```

2022-12-24 15:27 UTC, shun-shobon commented on .github/workflows/actionlint.yml
> +      - '.github/actions/**/**.yml'
globパターン的に書くならこうじゃないですか？
ついでにいうと、actionは`action.yml`で名前固定なのでワイルドカード指定は必要ないと思います。
```suggestion
      - '.github/workflows/*.yml'
      - '.github/actions/**/action.yml'
```

2022-12-24 15:30 UTC, m2en commented on .github/actions/publish/action.yml
>          node-version: '16'
[`d839db6` (#651)](https://github.com/approvers/OreOreBot2/pull/651/commits/d839db6f6fc89a019201edfbbde7b186af81c599) でまとめて修正しました

2022-12-25 08:56 UTC, shun-shobon submitted a review, later dismissed
LGTM 👍

2022-12-25 09:36 UTC, MikuroXina approved these changes

2022-12-25 09:37 UTC, merged