chore: OreOreBot2 のパッケージマネージャーを yarn v3 に移行する
approvers/OreOreBot2 pull request #662
Opened 2023-01-08 08:11 UTC by m2en

### Details of implementation (実施内容)

OreOreBot2 のパッケージマネージャーを yarn v1 から v2 に移行しました。

Yarn PnP は使っていません。多分

2023-01-08 08:14 UTC, MikuroXina requested changes
CI のログでこう表示されているので, CI の方のインストール部分も更新しておいてください
```
The --frozen-lockfile option is deprecated; use --immutable and/or --immutable-cache instead
```

2023-01-08 08:17 UTC, shun-shobon requested changes

2023-01-08 08:17 UTC, shun-shobon commented on .yarnrc.yml
> +yarnPath: .yarn/releases/yarn-3.3.1.cjs
need 改行

2023-01-08 08:18 UTC, m2en commented on .yarnrc.yml
> +yarnPath: .yarn/releases/yarn-3.3.1.cjs
血液型A型なので、気になって外しました...... すみません

2023-01-10 15:21 UTC, shun-shobon requested changes

2023-01-10 15:51 UTC, MikuroXina requested changes
`package.json` の `engines` の指定から `"yarn": "1.x"` を取り除いておいてください.

2023-01-10 15:51 UTC, shun-shobon approved these changes
LGTM!

2023-01-10 15:55 UTC, MikuroXina approved these changes

2023-01-10 15:55 UTC, shun-shobon approved these changes

2023-01-10 15:58 UTC, merged