fix: 引数の型を EmojiEvent に修正
approvers/OreOreBot2 pull request #700
Opened 2023-02-03 17:51 UTC by MikuroXina

### Type of Change:

型の修正

### Details of implementation (実施内容)

`EmojiLog` の第 1 引数の型は `EmojiEvent` となるべきですがなぜか `RoleEvent` 型になっていたので修正しました.

2023-02-03 18:02 UTC, m2en requested changes

2023-02-03 18:02 UTC, m2en commented on src/service/emoji-log.ts
> +  async on(event: EmojiEvent, role: EmojiData): Promise<void> {
ここも `role` じゃなくて `emoji`

2023-02-03 18:09 UTC, MikuroXina commented on src/service/emoji-log.ts
> +  async on(event: EmojiEvent, role: EmojiData): Promise<void> {
分割代入のほうが適していそうでしたので, 4a702e2 にてそのように修正しました.

2023-02-04 03:08 UTC, m2en approved these changes

2023-02-04 04:26 UTC, merged