コントリビューターに向けてのドキュメントの追加
approvers/OreOreBot2 pull request #95
Opened 2022-03-23 15:42 UTC by merunno

* #88

2022-03-23 16:20 UTC, merunno commented on CONTRIBUTING.md
> +[README.md](./README.md) にあるように、このプロジェクトは限界開発鯖のBot [【はらちょ】](https://github.com/approvers/OreOreBot) を discord.js +
```suggestion
このプロジェクトは限界開発鯖のBot [【はらちょ】](https://github.com/approvers/OreOreBot) を discord.js +
```
Todo: 最初の文書いらない

2022-03-23 16:20 UTC, merunno commented on CONTRIBUTING.md
> +
```suggestion
1. 当リポジトリをフォークしてください。
2. リポジトリをクローンしてください。

```
これだと意味がない

2022-03-24 10:52 UTC, MikuroXina requested changes

2022-03-24 10:52 UTC, MikuroXina commented on CONTRIBUTING.md
> +$ git checkout -b <branch-name>
シェルのコードブロックにして, `$` は取り除いてください. 他も同様です
```suggestion
```sh
git checkout -b <branch-name>
```

2022-03-24 10:52 UTC, MikuroXina commented on CONTRIBUTING.md
> +5. 開発が終了したら `GitHub / pull request` で新規 pull request を作成してください。
コードではないので地の文にしてほしいです.
```suggestion
5. 開発が終了したら GitHub からで新規 pull request を作成してください。
```

2022-03-24 10:52 UTC, MikuroXina commented on CONTRIBUTING.md
> +  - `<file-name>` は機能の処理を行うファイルと同じ名前にし、 `.` は使用しないようにしてください。
「`.` は使用しないように～」の意図が少しわかりにくいです. おそらく不要かと

2022-03-24 10:52 UTC, MikuroXina commented on CONTRIBUTING.md
> +  - [Conventional Commit - Japanese](https://conventionalcommits.org/ja/)
直接リンクにした方がよいでしょう.
```suggestion
コミットメッセージを書く際は [**Conventional Commit**](https://conventionalcommits.org/ja/) に従ってください。
```

2022-03-24 11:18 UTC, MikuroXina commented on CONTRIBUTING.md
> +2. リポジトリをクローンしてください。
どちらのリポジトリなのかわかりにくいので, 「フォークしたリポジトリ」のような表現のほうがよいかと

2022-03-24 11:19 UTC, MikuroXina commented on CONTRIBUTING.md
> +...
シェルで操作を続けるわけではないので `...` は不要かと
```suggestion
```

2022-03-24 11:20 UTC, MikuroXina commented on CONTRIBUTING.md
> +git push
これステージだけしてコミットせずに `push` しているので変です

2022-03-24 11:21 UTC, MikuroXina commented on CONTRIBUTING.md
> +4. 開発を行います。
説明と下記の内容が合ってないので, もう少し具体的に
```suggestion
4. 開発を行い、その内容を GitHub へアップロードします。
```

2022-03-24 11:21 UTC, MikuroXina commented on CONTRIBUTING.md
> +5. 開発が終了したら GitHub からで新規 pull request を作成してください。
少し日本語がおかしい
```suggestion
5. 開発が終了したら GitHub から当リポジトリの `main` ブランチへ新規 pull request を作成してください。
```

2022-03-24 11:23 UTC, MikuroXina commented on CONTRIBUTING.md
> +  - `<file-name>` は機能の処理を行うファイルと同じ名前にし、 `.test.ts` との競合を回避するため、`<file-name>` で `.` は含めないようにしてください。
「`.test.ts` との競合を回避するため」は理由として不十分かと. 別の場所で「ファイル名を `kebab-case`にするというコーディング規約である」ことを明示するほうがよいと思います.

2022-03-24 11:24 UTC, MikuroXina commented on README.md
> +(開発に関する質問は [Issue](https://github.com/approvers/OreOreBot2/issues) か 限界開発鯖内 プロジェクトカテゴリー [`#新生はらちょ`](https://discordapp.com/channels/683939861539192860/947208529561927710) までどうぞ。)
カテゴリーというよりかはチャンネルかと
```suggestion
(開発に関する質問は [Issue](https://github.com/approvers/OreOreBot2/issues) か 限界開発鯖内 プロジェクトチャンネル [`#新生はらちょ`](https://discordapp.com/channels/683939861539192860/947208529561927710) までどうぞ。)
```

2022-03-24 11:53 UTC, MikuroXina requested changes

2022-03-24 11:53 UTC, MikuroXina commented on CONTRIBUTING.md
> +    - ファイル名を `kabeb-case` にするというコーティング規約に従ってください。
これは「テストについて」の章で書くのではなく, それより前に「コーディング規約」の章を設けて記載すべきです

2022-03-24 12:33 UTC, MikuroXina approved these changes

2022-03-24 12:35 UTC, merged