feat: スラッシュコマンドの対応
approvers/OreOreBot2 pull request #974
Opened 2023-08-13 15:38 UTC by MikuroXina

Close #560.

### Type of Change:

機能の追加, 環境変数の追加

### Details of implementation (実施内容)

コマンドのスキーマの情報を元に, これらをスラッシュコマンドのスキーマへ加工して Discord API に送信するようにしました

この実装のために既存のコマンドのスキーマでは情報が不足していました. 根本的な対策として, スキーマの `interface` 定義を改修し, 不足していたフィールド `description` をそれぞれのスキーマの記述に追記しました.

2023-08-13 17:37 UTC, m1sk9 requested changes

2023-08-13 17:37 UTC, m1sk9 commented on src/server/index.ts
> +}
コマンドの登録が毎回走るのは起動に時間がかかりそうなので控えたいという顔をしています。
一番スマートなのは新しい Features Flag を作ることでしょうか....

2023-08-13 17:37 UTC, m1sk9 commented on README.md
> +| `FEATURE`         | 有効にする機能のカンマ区切り文字列、デフォルト値は全ての機能。`"MESSAGE_CREATE"`, `"MESSAGE_UPDATE"`, `"COMMAND"`, `"VOICE_ROOM"`, `"ROLE"`, `"EMOJI"`, `"SLASH_COMMAND"` を組み合わせ可能。 | False |
https://github.com/approvers/OreOreBot2/blob/812ad2e8ae9c2e42348846cb7fda74d9a076f4d4/.env.example#L1-L5

[`.env.example`](https://github.com/approvers/OreOreBot2/blob/main/.env.example) に `APPLICATION_ID` を追加してほしいです

2023-08-13 17:39 UTC, MikuroXina commented on README.md
> +| `FEATURE`         | 有効にする機能のカンマ区切り文字列、デフォルト値は全ての機能。`"MESSAGE_CREATE"`, `"MESSAGE_UPDATE"`, `"COMMAND"`, `"VOICE_ROOM"`, `"ROLE"`, `"EMOJI"`, `"SLASH_COMMAND"` を組み合わせ可能。 | False |
649cb3b で対応しました

2023-08-13 17:41 UTC, MikuroXina commented on src/server/index.ts
> +}
コマンドの情報を取得してきて, 変更が必要なところだけ PUT するような感じにしてみようと思います. それと今気づきましたが, これだとコマンドの機能が減った場合にその登録を削除する処理がされないのは直しておきたいです

2023-08-14 03:15 UTC, MikuroXina commented on src/server/index.ts
> +}
f3642b7 と 4796e4b にて起動時のパフォーマンスおよびリクエストを最適化しました. コマンドが一切登録されていない初回起動は少し遅いですが, 以降の更新は高速に行われます

2023-08-14 12:31 UTC, m1sk9 commented on src/server/index.ts
> +    console.log('コマンドの登録に成功しました。');
コマンド登録ロジックの実行時に `needToUpdate` の `.length` が返す値が `0` のようです

![CleanShot 2023-08-14 at 21 31 47](https://github.com/approvers/OreOreBot2/assets/82575685/6f466700-c93d-4064-b1ac-f169b63df0a4)

2023-08-14 12:41 UTC, m1sk9 commented on src/service/command/channel-info.ts
> +      name: 'channel_id',
ここ `target` だったりしませんか?

2023-08-14 12:41 UTC, m1sk9 commented
レビューした分と合わせて一部のコマンドが正しく実行できないようです。

- /channelinfo

```shell
CombinedPropertyError: Received one or more errors
    at ArrayValidator.handle (/Users/m1sk9/project/github.com/approvers/OreOreBot2/node_modules/@sapphire/shapeshift/src/validators/ArrayValidator.ts:102:17)
    at ArrayValidator.parse (/Users/m1sk9/project/github.com/approvers/OreOreBot2/node_modules/@sapphire/shapeshift/src/validators/BaseValidator.ts:103:2)
    at EmbedBuilder.spliceFields (/Users/m1sk9/project/github.com/approvers/OreOreBot2/node_modules/@discordjs/builders/src/messages/embed/Embed.ts:157:29)
    at EmbedBuilder.setFields (/Users/m1sk9/project/github.com/approvers/OreOreBot2/node_modules/@discordjs/builders/src/messages/embed/Embed.ts:174:8)
    at convertEmbed (file:///Users/m1sk9/project/github.com/approvers/OreOreBot2/src/adaptor/embed-convert.ts:31:11)
    at Object.reply (file:///Users/m1sk9/project/github.com/approvers/OreOreBot2/src/adaptor/proxy/command.ts:146:20)
    at ChannelInfo.on (file:///Users/m1sk9/project/github.com/approvers/OreOreBot2/src/service/command/channel-info.ts:52:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DiscordCommandProxy.onInteractionCreate (file:///Users/m1sk9/project/github.com/approvers/OreOreBot2/src/adaptor/proxy/command.ts:131:5) {
  errors: [ [ 1, [CombinedPropertyError] ] ]
}
```

- /help
 - 既に返信済みのインタラクションに応答してしまったようです。

```shell
Error [InteractionAlreadyReplied]: The reply to this interaction has already been sent or deferred.
    at ChatInputCommandInteraction.reply (/Users/m1sk9/project/github.com/approvers/OreOreBot2/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:102:46)
    at Object.replyPages (file:///Users/m1sk9/project/github.com/approvers/OreOreBot2/src/adaptor/proxy/command.ts:215:37)
    at HelpCommand.on (file:///Users/m1sk9/project/github.com/approvers/OreOreBot2/src/service/command/help.ts:33:19)
    at file:///Users/m1sk9/project/github.com/approvers/OreOreBot2/src/runner/command.ts:26:17
    at DiscordCommandProxy.onInteractionCreate (file:///Users/m1sk9/project/github.com/approvers/OreOreBot2/src/adaptor/proxy/command.ts:131:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'InteractionAlreadyReplied'
}
```

2023-08-14 13:13 UTC, MikuroXina commented on src/server/index.ts
> +    console.log('コマンドの登録に成功しました。');
0b6073d で修正しました

2023-08-14 13:15 UTC, MikuroXina commented on src/service/command/channel-info.ts
> +      name: 'channel_id',
何を入れても Discord 上での引数の名前に影響するだけですが, 0b9c213 でそのようにしておきました

2023-08-14 13:17 UTC, m1sk9 commented on src/service/command/channel-info.ts
> +      name: 'channel_id',
`user` と `role` が `target` なのに、 `channel` だけこれだったので実行できないのはこれが原因かと, OKです

2023-08-14 15:21 UTC, m1sk9 approved these changes

2023-08-14 15:21 UTC, merged